"""initial_v2

Revision ID: fc4125d7a33c
Revises: 
Create Date: 2026-02-28 03:51:46.925615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc4125d7a33c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'running', 'paused', 'completed', name='experimentstatus'), nullable=False),
    sa.Column('control_model_id', sa.String(length=200), nullable=False),
    sa.Column('treatment_model_id', sa.String(length=200), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('control_executions', sa.Integer(), nullable=False),
    sa.Column('treatment_executions', sa.Integer(), nullable=False),
    sa.Column('control_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('treatment_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_sample_size', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_experiments_agent_id'), 'ab_test_experiments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_ab_test_experiments_user_id'), 'ab_test_experiments', ['user_id'], unique=False)
    op.create_table('agent_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('ix_agent_configs_active', 'agent_configs', ['id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_agent_configs_created_at', 'agent_configs', ['created_at'], unique=False)
    op.create_index('ix_agent_configs_id_version_desc', 'agent_configs', ['id', sa.literal_column('version DESC')], unique=False)
    op.create_table('agent_fine_tuning_configs',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('auto_retrain_enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_retrain_threshold', sa.Integer(), nullable=False),
    sa.Column('default_base_model', sa.String(length=100), nullable=True),
    sa.Column('default_provider', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector_type', sa.String(length=20), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('webhook_secret', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_agent_id'), 'connectors', ['agent_id'], unique=False)
    op.create_table('execution_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('original_response', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_feedback_agent_id'), 'execution_feedback', ['agent_id'], unique=False)
    op.create_index(op.f('ix_execution_feedback_execution_id'), 'execution_feedback', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_feedback_user_id'), 'execution_feedback', ['user_id'], unique=False)
    op.create_index('ix_feedback_agent_rating', 'execution_feedback', ['agent_id', 'rating'], unique=False)
    op.create_table('fine_tuning_datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('building', 'ready', 'uploaded', 'error', name='datasetstatus'), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('example_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=True),
    sa.Column('openai_file_id', sa.String(length=100), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_tuning_datasets_agent_id'), 'fine_tuning_datasets', ['agent_id'], unique=False)
    op.create_index(op.f('ix_fine_tuning_datasets_user_id'), 'fine_tuning_datasets', ['user_id'], unique=False)
    op.create_table('graph_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_index('ix_graph_configs_active', 'graph_configs', ['id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('ix_graph_configs_created_at', 'graph_configs', ['created_at'], unique=False)
    op.create_index('ix_graph_configs_id_version_desc', 'graph_configs', ['id', sa.literal_column('version DESC')], unique=False)
    op.create_table('recall_test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('suite_name', sa.String(length=200), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('avg_recall_at_k', sa.Float(), nullable=False),
    sa.Column('avg_mrr', sa.Float(), nullable=False),
    sa.Column('avg_ndcg', sa.Float(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recall_test_runs_created_at', 'recall_test_runs', ['created_at'], unique=False)
    op.create_index('ix_recall_test_runs_suite_name', 'recall_test_runs', ['suite_name'], unique=False)
    op.create_table('user_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_cross_conversation_search', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'user', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('local', 'platform', name='usersource'), nullable=False),
    sa.Column('platform_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_platform_user_id'), 'users', ['platform_user_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supervisor_mode', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_id'), 'conversations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('dataset_examples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('curation_status', sa.Enum('pending', 'approved', 'rejected', name='curationstatus'), nullable=False),
    sa.Column('curated_by', sa.String(length=36), nullable=True),
    sa.Column('curated_at', sa.DateTime(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fine_tuning_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dataset_examples_curation', 'dataset_examples', ['dataset_id', 'curation_status'], unique=False)
    op.create_index(op.f('ix_dataset_examples_dataset_id'), 'dataset_examples', ['dataset_id'], unique=False)
    op.create_table('fine_tuning_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.Enum('openai', 'local_export', name='jobprovider'), nullable=False),
    sa.Column('base_model', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'validating', 'training', 'completed', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('stream_task_id', sa.String(length=36), nullable=True),
    sa.Column('openai_job_id', sa.String(length=100), nullable=True),
    sa.Column('openai_model_id', sa.String(length=200), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['fine_tuning_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_tuning_jobs_agent_id'), 'fine_tuning_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_fine_tuning_jobs_dataset_id'), 'fine_tuning_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_fine_tuning_jobs_stream_task_id'), 'fine_tuning_jobs', ['stream_task_id'], unique=False)
    op.create_index(op.f('ix_fine_tuning_jobs_user_id'), 'fine_tuning_jobs', ['user_id'], unique=False)
    op.create_table('memory_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.Enum('AGENT', 'USER_PROFILE', 'CONVERSATION', 'CROSS_CONVERSATION', name='memoryscope'), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('tier', sa.Enum('BUFFER', 'SUMMARY', 'VECTOR', 'ARCHIVE', name='memorytier'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_entries_scope_id'), 'memory_entries', ['scope_id'], unique=False)
    op.create_index(op.f('ix_memory_entries_user_id'), 'memory_entries', ['user_id'], unique=False)
    op.create_index('ix_memory_scope_tier', 'memory_entries', ['scope', 'scope_id', 'tier'], unique=False)
    op.create_table('rag_collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scope', sa.Enum('global', 'group', 'agent', name='ragscope'), nullable=False),
    sa.Column('allowed_groups', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_group_members',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('execution_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_type', sa.Enum('agent', 'graph', 'supervisor', name='executiontype'), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('graph_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'awaiting_approval', 'completed', 'failed', 'stopped', name='executionstatus'), nullable=False),
    sa.Column('config_version', sa.Integer(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=True),
    sa.Column('stream_task_id', sa.String(length=100), nullable=True),
    sa.Column('input_prompt', sa.Text(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('experiment_variant', sa.String(length=20), nullable=True),
    sa.Column('approval_node_id', sa.String(length=100), nullable=True),
    sa.Column('approval_timeout_at', sa.DateTime(), nullable=True),
    sa.Column('approval_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('approval_decision', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_approval_status', 'execution_runs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_runs_agent_id'), 'execution_runs', ['agent_id'], unique=False)
    op.create_index('ix_execution_runs_experiment', 'execution_runs', ['experiment_id', 'experiment_variant'], unique=False)
    op.create_index(op.f('ix_execution_runs_experiment_id'), 'execution_runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_graph_id'), 'execution_runs', ['graph_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_model'), 'execution_runs', ['model'], unique=False)
    op.create_index(op.f('ix_execution_runs_stream_task_id'), 'execution_runs', ['stream_task_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_user_id'), 'execution_runs', ['user_id'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['rag_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_documents_collection_id'), 'rag_documents', ['collection_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['execution_id'], ['execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index('ix_message_conversation_time', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('parent_step_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'awaiting_approval', 'completed', 'failed', 'stopped', name='executionstatus'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('tokens_prompt', sa.Integer(), nullable=False),
    sa.Column('tokens_completion', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_step_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_steps_run_id'), 'execution_steps', ['run_id'], unique=False)
    op.create_index('ix_step_run_number', 'execution_steps', ['run_id', 'step_number'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_collection', 'rag_chunks', ['collection_id'], unique=False)
    op.create_index('ix_chunk_document_index', 'rag_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_rag_chunks_collection_id'), 'rag_chunks', ['collection_id'], unique=False)
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_collection_id'), table_name='rag_chunks')
    op.drop_index('ix_chunk_document_index', table_name='rag_chunks')
    op.drop_index('ix_chunk_collection', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index('ix_step_run_number', table_name='execution_steps')
    op.drop_index(op.f('ix_execution_steps_run_id'), table_name='execution_steps')
    op.drop_table('execution_steps')
    op.drop_index('ix_message_conversation_time', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_rag_documents_collection_id'), table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index(op.f('ix_execution_runs_user_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_stream_task_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_model'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_graph_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_experiment_id'), table_name='execution_runs')
    op.drop_index('ix_execution_runs_experiment', table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_agent_id'), table_name='execution_runs')
    op.drop_index('ix_execution_approval_status', table_name='execution_runs')
    op.drop_table('execution_runs')
    op.drop_table('user_group_members')
    op.drop_table('rag_collections')
    op.drop_index('ix_memory_scope_tier', table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_user_id'), table_name='memory_entries')
    op.drop_index(op.f('ix_memory_entries_scope_id'), table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index(op.f('ix_fine_tuning_jobs_user_id'), table_name='fine_tuning_jobs')
    op.drop_index(op.f('ix_fine_tuning_jobs_stream_task_id'), table_name='fine_tuning_jobs')
    op.drop_index(op.f('ix_fine_tuning_jobs_dataset_id'), table_name='fine_tuning_jobs')
    op.drop_index(op.f('ix_fine_tuning_jobs_agent_id'), table_name='fine_tuning_jobs')
    op.drop_table('fine_tuning_jobs')
    op.drop_index(op.f('ix_dataset_examples_dataset_id'), table_name='dataset_examples')
    op.drop_index('ix_dataset_examples_curation', table_name='dataset_examples')
    op.drop_table('dataset_examples')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_platform_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_groups')
    op.drop_index('ix_recall_test_runs_suite_name', table_name='recall_test_runs')
    op.drop_index('ix_recall_test_runs_created_at', table_name='recall_test_runs')
    op.drop_table('recall_test_runs')
    op.drop_index('ix_graph_configs_id_version_desc', table_name='graph_configs')
    op.drop_index('ix_graph_configs_created_at', table_name='graph_configs')
    op.drop_index('ix_graph_configs_active', table_name='graph_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_table('graph_configs')
    op.drop_index(op.f('ix_fine_tuning_datasets_user_id'), table_name='fine_tuning_datasets')
    op.drop_index(op.f('ix_fine_tuning_datasets_agent_id'), table_name='fine_tuning_datasets')
    op.drop_table('fine_tuning_datasets')
    op.drop_index('ix_feedback_agent_rating', table_name='execution_feedback')
    op.drop_index(op.f('ix_execution_feedback_user_id'), table_name='execution_feedback')
    op.drop_index(op.f('ix_execution_feedback_execution_id'), table_name='execution_feedback')
    op.drop_index(op.f('ix_execution_feedback_agent_id'), table_name='execution_feedback')
    op.drop_table('execution_feedback')
    op.drop_index(op.f('ix_connectors_agent_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_table('agent_fine_tuning_configs')
    op.drop_index('ix_agent_configs_id_version_desc', table_name='agent_configs')
    op.drop_index('ix_agent_configs_created_at', table_name='agent_configs')
    op.drop_index('ix_agent_configs_active', table_name='agent_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_table('agent_configs')
    op.drop_index(op.f('ix_ab_test_experiments_user_id'), table_name='ab_test_experiments')
    op.drop_index(op.f('ix_ab_test_experiments_agent_id'), table_name='ab_test_experiments')
    op.drop_table('ab_test_experiments')
    # ### end Alembic commands ###
