import {
  Search,
  MessageSquare,
  HardDrive,
  Mail,
  Calendar,
  BookOpen,
  Database,
  Kanban,
  Ticket,
  Github,
  Flame,
  Brain,
  Folder,
  Send,
  BarChart,
  GitBranch,
  AlertTriangle,
  Cloud,
  CreditCard,
  Briefcase,
  ShoppingCart,
  MessageCircle,
  FileText,
  LayoutGrid,
  Terminal,
  Globe,
} from "lucide-react";

export const ICON_MAP: Record<string, React.ElementType> = {
  search: Search,
  "message-square": MessageSquare,
  "hard-drive": HardDrive,
  mail: Mail,
  calendar: Calendar,
  "book-open": BookOpen,
  database: Database,
  kanban: Kanban,
  ticket: Ticket,
  github: Github,
  flame: Flame,
  brain: Brain,
  folder: Folder,
  send: Send,
  "bar-chart": BarChart,
  "git-branch": GitBranch,
  "alert-triangle": AlertTriangle,
  cloud: Cloud,
  "credit-card": CreditCard,
  briefcase: Briefcase,
  "shopping-cart": ShoppingCart,
  "message-circle": MessageCircle,
  "file-text": FileText,
  "layout-grid": LayoutGrid,
  terminal: Terminal,
  globe: Globe,
};

export const CATEGORY_LABELS: Record<string, string> = {
  search: "Search",
  communication: "Communication",
  productivity: "Productivity",
  database: "Database",
  "project-management": "Project Management",
  development: "Development",
  utility: "Utility",
  devops: "DevOps",
  "data-analytics": "Data & Analytics",
  ai: "AI / ML",
  automation: "Automation",
  finance: "Finance",
};
